// Shared movement constants
export const BASE_FRAME_SECONDS = 1 / 60

export const MOVEMENT_CONFIG = {
  ACCELERATION: 0.15,
  DECELERATION: 0.20,
  ROTATION_SPEED: 0.12,
  MAX_SPEED: 0.9,
  MIN_SPEED: 0.05,
  COLLISION_BUFFER: 8,
  MIN_UNIT_DISTANCE: 24,
  AVOIDANCE_FORCE: 0.5,
  BACKWARD_MOVE_THRESHOLD: 0.5,
  FORCE_FIELD_RADIUS: 36,
  FORCE_FIELD_STRENGTH: 2.5,
  FORCE_FIELD_FALLOFF: 2.0
}

export const LOCAL_LOOKAHEAD_STEPS = [0.5, 1.0, 1.5]
export const LOCAL_LOOKAHEAD_STRENGTH = 0.8

export const UNIT_COLLISION_MIN_DISTANCE = MOVEMENT_CONFIG.MIN_UNIT_DISTANCE
